### ISSUE TITLE
[Docs] Use pubspec's ref attribute maybe?

### ISSUE THREAD

**Issue by raveesh-me** [razorpay/razorpay-flutter#3]
Hi!
In the user's guide, 

```
razorpay_flutter:
  git:
    url: git://github.com/razorpay/razorpay-flutter.git#f7ea14a

```

This is the format given to import the package to the flutter project. However, this ends up in error message: 
```
Running "flutter packages get" in dole-flutter-app...           
Git error. Command: git fetch
fatal: not a git repository (or any of the parent directories): .git
```

On MacOS, with everything else to latest.

Please consider using ref: attribute as mentioned in the official pub docs.
`https://dart.dev/tools/pub/dependencies#git-packages`

Also, this works fine:

```
  razorpay_flutter:
    git:
      url: git://github.com/razorpay/razorpay-flutter.git
      ref: "f7ea14a"
```
