### ISSUE TITLE
Namespace error in application

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [razorpay/razorpay-flutter#360]
when adding this package to flutter android throwing namespace error can pls update this lib with new  support android version

in release to make sure your issue has not already been fixed: 

## Flutter Version :
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (7 days ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4

**Comment by vivekshindhe** [comment]
@sunil-singh-chaudhary Can you please post the error message that you see?

**Comment by sunil-singh-chaudhary** [comment]
> @sunil-singh-chaudhary Can you please post the error message that you see?

Namespace not specified. Please specify a namespace in the module's build.gradle i have update my android project to compilesdk version to 34

**Comment by OutdatedGuy** [comment]
Hi @sunil-singh-chaudhary, you can use below code till this is fixed

```yaml
dependencies:
  razorpay_flutter:
    git:
      url: https://github.com/OutdatedGuy/razorpay-flutter
      ref: stable
```
